baseURL = 'https://rpoovey.github.io/ranchhandapartments/'
languageCode = 'en-us'
# title = 'Ranchhand Apartments'
enableRobotsTXT = true
theme = 'ananke'
sectionPagesMenu = "main"
# canonifyURLs = true
# [services.googleAnalytics]
# id = ''

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = "/images/favicon.jpg"
# site_logo = "/images/favicon.jpg"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover fill bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"

[params.ananke.social.share]
networks = ["email", "facebook", "bluesky", "linkedin"]

# [params.ananke.social.follow]
# networks = ["facebook", "bluesky", "linkedin"]
# #
# [params.ananke.social.facebook]
# username = "patrick.kollitsch"
# profilelink = "https://www.facebook.com/patrick.kollitsch"
#
# [params.ananke.social.linkedin]
# username = "patrickkollitsch"
#
# [params.ananke.social.bluesky]
# username = "kollitsch.dev"
